### ISSUE TITLE
Empty output with own data

### ISSUE THREAD

**Issue by ghost** [libing64/slam2d#2]
Hi, firstly, thanks for sharing your work!

After running your algorithm with my recorded data, it seems not to give any output when I play the bag file.
I just used horizontal 2D laser data, without IMU, I guess that's fine. Could it be because I don't provide intensity values?

When I run the launch file, a fatal error arises. I am not sure if this is the problem because when I use Cartographer (sample) data it also appears this error, but the algorithm works well (new topics are correctly published and rviz visualization looks good).

I can't find any bug in my input data. Do you know why this problem could be happening?

![slam2d_error](https://user-images.githubusercontent.com/72814058/114542724-8d808f80-9c58-11eb-82d0-f2e791871cbe.JPG)

![slam2d_rviz](https://user-images.githubusercontent.com/72814058/114543514-96be2c00-9c59-11eb-9e46-d3fb81e64d67.JPG)

**Comment by libing64** [comment]
@polbolso You should modify the path to your own rosbag in launch file.

**Comment by ghost** [comment]
Thanks! I have included the path to my bag file and the error opening the file disappeared. But now there is another error that prevents me from showing anything in rviz.

![slam2d_error2](https://user-images.githubusercontent.com/72814058/114738263-19251980-9d48-11eb-9003-7c07c2a322c0.JPG)

Is it something related to my input data? As I see something about the topic 'horizontal_laser_2d' mentioned in the error.

**Comment by libing64** [comment]
@polbolso Please print the result of 
"rostopic list", "rostopic info horizontal_laser_2d" and "rostopic info your_own_laser_topic"

**Comment by ghost** [comment]
I saved my 2D LiDAR raw data into a bag file, under the topic 'horizontal_laser_2d', so I guess in this case this is the same as 'my_own_laser_topic".

![rostopic](https://user-images.githubusercontent.com/72814058/115124121-dd48b900-9fc0-11eb-8198-1af6a7ff0299.jpg)

After playing my input bag file, this is what the recorded bag file shows (I exited after 50 s), only the initial pose is obtained as output:

![image](https://user-images.githubusercontent.com/72814058/115124274-a030f680-9fc1-11eb-9ff2-8e25709c26b2.png)

**Comment by libing64** [comment]
@polbolso Can you share your rosbag? And I would try to debug with your data.

**Comment by ghost** [comment]
[20210330_132458.zip](https://github.com/libing64/slam2d/files/6331101/20210330_132458.zip)

Thanks!

**Comment by ghost** [comment]
Hi @libing64, have you already tried to debug it with my data?

**Comment by libing64** [comment]
@polbolso Yeah, it crashed with your data and I am trying to figure out why.

**Comment by libing64** [comment]
@polbolso The header of laser scan has invalid data, for example, angle_min and angle_max.
```
header: 
  seq: 20
  stamp: 
    secs: 46833
    nsecs: 118433999
  frame_id: "horizontal_laser_link"
angle_min: 5.454115390777588
angle_max: 5.8087310791015625
angle_increment: 0.0015219557099044323
time_increment: 9.699571137389285e-07
scan_time: 0.00022600000374950469
range_min: 0.4160001873970032
range_max: 45.38550567626953
```
